version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      docker: 19
  build:
    commands:
      - mvn clean package -X

artifacts:
  files:
    - target/**/*
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'